<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */

$env = getenv('APP_ENV') ?: 'production';

$modules = array(
    'Authenticate',
    'Common',
    'Search',
    'Users',
    'Api',
);

if ($env == 'development'){
//    $modules[] = 'ZendDeveloperTools';
}
return array(
    'modules' => $modules,
    'module_listener_options' => array(
        'config_glob_paths' => array('config/autoload/{,*.}{global,local}.php'),
        'module_paths' => array(
            './module',
            './vendor'
            )
        )
    );
