<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'listeners' =>  array(
        'EventListeners',
    ),
    'modules' => array(
        'ZendDeveloperTools',
        'Listeners',
//        'DoctrineModule',
//        'DoctrineORMModule',
        'Authenticate',
        'Common',
//        'ZFTool',
        'Search',
        'Users',
        'Api',
        'Logging',
        ),
    'module_listener_options' => array(
        'config_glob_paths' => array('config/autoload/{,*.}{global,local}.php'),
        'module_paths' => array(
            './module',
            './vendor'
            )
        )
    );
